[package]
name = "libdither"
version = "0.1.0"
authors = ["zyansheep <zyansheep@github.com>"]
edition = "2021"
description = "Wraps Node API with platform-specific features"
default-run = "libdither"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
futures = "0.3.26"
log = "0.4.17"

node = { path = "node" }
serde = { version = "^1", features = ["derive"] }
async-std = { version = "1.13", features = ["attributes"] }
# Important: rkyv endianness must be little-endian everywhere
rkyv = { version = "0.8" }
thiserror = "2"
rustyline-async = "0.4"
simplelog = "^0.12"
snow = "0.9"
bevy_ecs = "0.10"
rand = "0.9"
bincode = "1.3.3"
rkyv_codec = { version = "0.4.0", git = "https://github.com/zyansheep/rkyv_codec" }
serde_json = "1"
futures-delay-queue = "0.6"

[[bin]]
name = "sim_bin"
path = "src/sim_main.rs"

[[bin]]
name = "libdither"
path = "src/main.rs"

[patch.crates-io]
rkyv_codec = { git = 'https://github.com/zyansheep/rkyv_codec' }
