[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async
async-std = { version = "1.12.0", features = ["unstable"] }
futures = "0.3.26"
thiserror = "1.0.38"
eyre = "0.6.8"

# ECS
bevy_ecs = "0.10"

# Serialization
# Important: rkyv endianness must be little-endian everywhere
rkyv = { version = "0.8" }                                                          # Zero-Copy Serialization
rkyv_codec = { version = "0.4.0", git = "https://github.com/zyansheep/rkyv_codec" }
serde = "^1"

# Data & Utilities
const-multihash = { git = "https://github.com/zyansheep/const-multihash" }

nalgebra = { version = "0.33", features = [
	"rkyv-serialize",
	"serde-serialize",
] }

num = "0.4.0"
log = "0.4.17"
derive_more = "0.99.17"
nnmf_nalgebra = "0.1.0"
argmin = { version = "0.10.0", features = ["serde"] }
rand = "0.9"
pin-project = "^1"
either = "1.15"
bytes = "1.10"
smallvec = { version = "2.0.0-alpha.11" }

# Encryption
snow = "0.9"
rustls = "0.23"
slice-ring-buffer = "0.3"
thingbuf = "0.1"
arc-swap = "1.7"
