# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/helper-validator-identifier-7.15.7" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.15.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.15.7.tgz";
        sha512 = "K4JvCtQqad9OY2+yTU8w+E82ywk/fe+ELNlt1G8z3bVGlZfn/hOcQQsUhGhW/N+tb3fxK800wLtKOE/aM0m72w==";
      };
    };
    "@babel/parser-7.15.8" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.15.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.15.8.tgz";
        sha512 = "BRYa3wcQnjS/nqI8Ac94pYYpJfojHVvVXJ97+IDCImX4Jc8W8Xv1+47enbruk+q1etOpsQNwnfFcNGw+gtPGxA==";
      };
    };
    "@babel/types-7.15.6" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.15.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.15.6.tgz";
        sha512 = "BPU+7QhqNjmWyDO0/vitH/CuhpV8ZmK1wpKva8nuyNF5MJfuRNWMc+hc14+u9xT93kvykMdncrJT19h74uB1Ig==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "assert-never-1.2.1" = {
      name = "assert-never";
      packageName = "assert-never";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-never/-/assert-never-1.2.1.tgz";
        sha512 = "TaTivMB6pYI1kXwrFlEhLeGfOqoDNdTxjCdwRfFFkEA30Eu+k48W34nlok2EYWJfFFzqaEmichdNM7th6M5HNw==";
      };
    };
    "babel-walk-3.0.0-canary-5" = {
      name = "babel-walk";
      packageName = "babel-walk";
      version = "3.0.0-canary-5";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-walk/-/babel-walk-3.0.0-canary-5.tgz";
        sha512 = "GAwkz0AihzY5bkwIY5QDR+LvsRQgB/B+1foMPvi0FZPMl5fjD7ICiznUiBdLYMH1QYe6vqu4gWYytZOccLouFw==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha1 = "c7ce28f36d4bcd9744e5ffc2c5fcde1c73261fc0";
      };
    };
    "constantinople-4.0.1" = {
      name = "constantinople";
      packageName = "constantinople";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/constantinople/-/constantinople-4.0.1.tgz";
        sha512 = "vCrqcSIq4//Gx74TXXCGnHpulY1dskqLTFGDmhrGxzeXL8lF8kvXv6mpNWlJj1uD4DW23D4ljAqbY4RRaaUZIw==";
      };
    };
    "doctypes-1.1.0" = {
      name = "doctypes";
      packageName = "doctypes";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctypes/-/doctypes-1.1.0.tgz";
        sha1 = "ea80b106a87538774e8a3a4a5afe293de489e0a9";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-intrinsic-1.1.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.1.1.tgz";
        sha512 = "kWZrnVM42QCiEA2Ig1bG8zjoIMOgxWwYCEeNdwY6Tv/cOSeGpcoX4pXHfKUxNKVoArnrEr2e9srnAxxGIraS9Q==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-symbols-1.0.2" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.2.tgz";
        sha512 = "chXa79rL/UC2KlX17jo3vRGz0azaWEx5tGqZg5pO3NUyEJVB17dMruQlzCCOfUvElghKcm5194+BCRvi2Rv/Gw==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "is-core-module-2.7.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.7.0.tgz";
        sha512 = "ByY+tjCciCr+9nLryBYcSD50EOGWt95c7tIsKTG1J2ixKKXPvF7Ej3AVd+UfDydAJom3biBGDBALaO79ktwgEQ==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-promise-2.2.2" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.2.2.tgz";
        sha512 = "+lP4/6lKUBfQjZ2pdxThZvLUAafmZb8OAxFb8XXtiQmS35INgr85hdOGoEs124ez1FCnZJt6jau/T+alh58QFQ==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "js-stringify-1.0.2" = {
      name = "js-stringify";
      packageName = "js-stringify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-stringify/-/js-stringify-1.0.2.tgz";
        sha1 = "1736fddfd9724f28a3682adc6230ae7e4e9679db";
      };
    };
    "jstransformer-1.0.0" = {
      name = "jstransformer";
      packageName = "jstransformer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransformer/-/jstransformer-1.0.0.tgz";
        sha1 = "ed8bf0921e2f3f1ed4d5c1a44f68709ed24722c3";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "nolQXZ/4L+bP/UGlkfaIujX9BKxGwmQ9OT4mOt5yvy8iK1h3wqTEJCijzGANTCCl9nWjY41juyAn2K3Q1hLLTg==";
      };
    };
    "pug-attrs-3.0.0" = {
      name = "pug-attrs";
      packageName = "pug-attrs";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-attrs/-/pug-attrs-3.0.0.tgz";
        sha512 = "azINV9dUtzPMFQktvTXciNAfAuVh/L/JCl0vtPCwvOA21uZrC08K/UnmrL+SXGEVc1FwzjW62+xw5S/uaLj6cA==";
      };
    };
    "pug-code-gen-3.0.2" = {
      name = "pug-code-gen";
      packageName = "pug-code-gen";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-code-gen/-/pug-code-gen-3.0.2.tgz";
        sha512 = "nJMhW16MbiGRiyR4miDTQMRWDgKplnHyeLvioEJYbk1RsPI3FuA3saEP8uwnTb2nTJEKBU90NFVWJBk4OU5qyg==";
      };
    };
    "pug-error-2.0.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.0.0.tgz";
        sha512 = "sjiUsi9M4RAGHktC1drQfCr5C5eriu24Lfbt4s+7SykztEOwVZtbFk1RRq0tzLxcMxMYTBR+zMQaG07J/btayQ==";
      };
    };
    "pug-filters-4.0.0" = {
      name = "pug-filters";
      packageName = "pug-filters";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-filters/-/pug-filters-4.0.0.tgz";
        sha512 = "yeNFtq5Yxmfz0f9z2rMXGw/8/4i1cCFecw/Q7+D0V2DdtII5UvqE12VaZ2AY7ri6o5RNXiweGH79OCq+2RQU4A==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "pug-linker-4.0.0" = {
      name = "pug-linker";
      packageName = "pug-linker";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-linker/-/pug-linker-4.0.0.tgz";
        sha512 = "gjD1yzp0yxbQqnzBAdlhbgoJL5qIFJw78juN1NpTLt/mfPJ5VgC4BvkoD3G23qKzJtIIXBbcCt6FioLSFLOHdw==";
      };
    };
    "pug-load-3.0.0" = {
      name = "pug-load";
      packageName = "pug-load";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-load/-/pug-load-3.0.0.tgz";
        sha512 = "OCjTEnhLWZBvS4zni/WUMjH2YSUosnsmjGBB1An7CsKQarYSWQ0GCVyd4eQPMFJqZ8w9xgs01QdiZXKVjk92EQ==";
      };
    };
    "pug-parser-6.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz";
        sha512 = "ukiYM/9cH6Cml+AOl5kETtM9NR3WulyVP2y4HOU45DyMim1IeP/OOiyEWRr6qk5I5klpsBnbuHpwKmTx6WURnw==";
      };
    };
    "pug-runtime-3.0.1" = {
      name = "pug-runtime";
      packageName = "pug-runtime";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-runtime/-/pug-runtime-3.0.1.tgz";
        sha512 = "L50zbvrQ35TkpHwv0G6aLSuueDRwc/97XdY8kL3tOT0FmhgG7UypU3VztfV/LATAvmUfYi4wNxSajhSAeNN+Kg==";
      };
    };
    "pug-strip-comments-2.0.0" = {
      name = "pug-strip-comments";
      packageName = "pug-strip-comments";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-strip-comments/-/pug-strip-comments-2.0.0.tgz";
        sha512 = "zo8DsDpH7eTkPHCXFeAk1xZXJbyoTfdPlNR0bK7rpOMuhBYb0f5qUVCO1xlsitYd3w5FQTK7zpNVKb3rZoUrrQ==";
      };
    };
    "pug-walk-2.0.0" = {
      name = "pug-walk";
      packageName = "pug-walk";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-walk/-/pug-walk-2.0.0.tgz";
        sha512 = "yYELe9Q5q9IQhuvqsZNwA5hfPkMJ8u92bQLIMcsMxf/VADjNtEYptU+inlufAFYcWdHlwNfZOEnOOQrZrcyJCQ==";
      };
    };
    "resolve-1.20.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz";
        sha512 = "wENBPt4ySzg4ybFQW2TT1zMQucPK95HSh/nq2CFTZVOGut2+pQvSsgtda4d26YrYcr067wjbmzOG8byDPBX63A==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha1 = "dc5e698cbd079265bc73e0377681a4e4e83f616e";
      };
    };
    "token-stream-1.0.0" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz";
        sha1 = "cc200eab2613f4166d27ff9afc7ca56d49df6eb4";
      };
    };
    "void-elements-3.1.0" = {
      name = "void-elements";
      packageName = "void-elements";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/void-elements/-/void-elements-3.1.0.tgz";
        sha1 = "614f7fbf8d801f0bb5f0661f5b2f5785750e4f09";
      };
    };
    "with-7.0.2" = {
      name = "with";
      packageName = "with";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/with/-/with-7.0.2.tgz";
        sha512 = "RNGKj82nUPg3g5ygxkQl0R937xLyho1J24ItRCBTr/m1YnZkzJy1hUiHUJrc/VlsDQzsCnInEGSg3bci0Lmd4w==";
      };
    };
  };
in
{
  pug = nodeEnv.buildNodePackage {
    name = "pug";
    packageName = "pug";
    version = "3.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/pug/-/pug-3.0.2.tgz";
      sha512 = "bp0I/hiK1D1vChHh6EfDxtndHji55XP/ZJKwsRqrz6lRia6ZC2OZbdAymlxdVFwd1L70ebrVJw4/eZ79skrIaw==";
    };
    dependencies = [
      sources."@babel/helper-validator-identifier-7.15.7"
      sources."@babel/parser-7.15.8"
      sources."@babel/types-7.15.6"
      sources."acorn-7.4.1"
      sources."asap-2.0.6"
      sources."assert-never-1.2.1"
      sources."babel-walk-3.0.0-canary-5"
      sources."call-bind-1.0.2"
      sources."character-parser-2.2.0"
      sources."constantinople-4.0.1"
      sources."doctypes-1.1.0"
      sources."function-bind-1.1.1"
      sources."get-intrinsic-1.1.1"
      sources."has-1.0.3"
      sources."has-symbols-1.0.2"
      sources."has-tostringtag-1.0.0"
      sources."is-core-module-2.7.0"
      sources."is-expression-4.0.0"
      sources."is-promise-2.2.2"
      sources."is-regex-1.1.4"
      sources."js-stringify-1.0.2"
      sources."jstransformer-1.0.0"
      sources."object-assign-4.1.1"
      sources."path-parse-1.0.7"
      sources."promise-7.3.1"
      sources."pug-attrs-3.0.0"
      sources."pug-code-gen-3.0.2"
      sources."pug-error-2.0.0"
      sources."pug-filters-4.0.0"
      sources."pug-lexer-5.0.1"
      sources."pug-linker-4.0.0"
      sources."pug-load-3.0.0"
      sources."pug-parser-6.0.0"
      sources."pug-runtime-3.0.1"
      sources."pug-strip-comments-2.0.0"
      sources."pug-walk-2.0.0"
      sources."resolve-1.20.0"
      sources."to-fast-properties-2.0.0"
      sources."token-stream-1.0.0"
      sources."void-elements-3.1.0"
      sources."with-7.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A clean, whitespace-sensitive template language for writing HTML";
      homepage = "https://pugjs.org";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
